/**
 * Report Helpers
 * Utility functions for generating consistent report formats
 */

/**
 * Get current user's full name from user object
 */
export const getGeneratedByName = (currentUser) => {
  if (!currentUser) return 'Unknown User';
  
  if (currentUser.firstName && currentUser.lastName) {
    return `${currentUser.firstName} ${currentUser.lastName}`;
  }
  
  if (currentUser.name) {
    return currentUser.name;
  }
  
  if (currentUser.email) {
    return currentUser.email;
  }
  
  return 'Unknown User';
};

/**
 * Format date and time for report generation
 */
export const getGeneratedDateTime = () => {
  const now = new Date();
  return now.toLocaleString('en-US', {
    month: 'short',
    day: '2-digit',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
    hour12: true
  });
};

/**
 * Generate report header HTML with filters
 */
export const generateReportHeader = (title, filters = []) => {
  const filtersHTML = filters.length > 0
    ? `
      <div class="filters-section">
        <strong>Active Filters:</strong>
        ${filters.map(f => `<span class="filter-badge">${f}</span>`).join('')}
      </div>
    `
    : '';

  return `
    <div class="report-header">
      <div class="company-name">David Salon</div>
      <h1>${title}</h1>
      ${filtersHTML}
    </div>
  `;
};

/**
 * Generate report footer HTML with generated by info
 */
export const generateReportFooter = (currentUser) => {
  const generatedBy = getGeneratedByName(currentUser);
  const generatedOn = getGeneratedDateTime();
  
  return `
    <div class="report-footer">
      <div class="footer-content">
        <div class="footer-left">
          <div>Generated by: <strong>${generatedBy}</strong></div>
        </div>
        <div class="footer-center">
          <span class="page-number"></span>
        </div>
        <div class="footer-right">
          <div>Generated on: <strong>${generatedOn}</strong></div>
        </div>
      </div>
    </div>
  `;
};

/**
 * Generate complete report styles including page numbers
 */
export const generateReportStyles = () => {
  return `
    <style>
      @page {
        size: Letter;
        margin: 0.4in 0.4in 0.75in 0.4in;
      }
      
      @media print {
        body {
          margin: 0;
          padding: 0;
          font-family: 'Poppins', Arial, sans-serif;
          font-size: 10pt;
          color: #000;
          -webkit-print-color-adjust: exact;
          print-color-adjust: exact;
          counter-reset: page 1;
        }
        
        header, footer {
          display: none;
        }
        
        .report-header {
          text-align: center;
          margin-bottom: 20px;
          padding-bottom: 10px;
          border-bottom: 2px solid #333;
        }
        
        .company-name {
          font-size: 14pt;
          font-weight: 600;
          color: #000;
          margin-bottom: 8px;
        }
        
        .report-header h1 {
          margin: 0 0 10px 0;
          font-size: 18pt;
          font-weight: bold;
          color: #000;
        }
        
        .filters-section {
          margin-top: 10px;
          text-align: center;
          font-size: 9pt;
        }
        
        .filter-badge {
          display: inline-block;
          padding: 2px 8px;
          margin: 2px 4px;
          background-color: #f0f0f0;
          border: 1px solid #ccc;
          border-radius: 4px;
          font-size: 8pt;
        }
        
        .report-footer {
          position: fixed;
          bottom: 0;
          left: 0;
          right: 0;
          padding: 8px 0.4in 0.25in 0.4in;
          border-top: 1px solid #333;
        }
        
        .footer-content {
          display: flex;
          justify-content: space-between;
          align-items: flex-start;
          font-size: 8pt;
        }
        
        .footer-left {
          text-align: left;
          flex: 1;
        }
        
        .footer-center {
          text-align: center;
          flex: 1;
        }
        
        .footer-right {
          text-align: right;
          flex: 1;
        }
        
        /* Page number styling - content will be injected by JavaScript */
        .page-number {
          font-weight: 600;
        }
        
        .page-number::before {
          content: "Page 1";
        }
        
        table {
          width: 100%;
          border-collapse: collapse;
          margin-bottom: 20px;
          page-break-inside: auto;
        }
        
        thead {
          display: table-header-group;
        }
        
        tbody {
          display: table-row-group;
        }
        
        tr {
          page-break-inside: avoid;
          page-break-after: auto;
        }
        
        th {
          background-color: #f5f5f5 !important;
          border: 1px solid #333;
          padding: 8px;
          text-align: left;
          font-weight: bold;
          font-size: 9pt;
        }
        
        td {
          border: 1px solid #666;
          padding: 6px 8px;
          font-size: 9pt;
        }
        
        .text-right {
          text-align: right;
        }
        
        .text-center {
          text-align: center;
        }
        
        .font-bold {
          font-weight: bold;
        }
        
        .summary-section {
          margin-top: 20px;
          padding: 10px;
          background-color: #f9f9f9;
          border: 1px solid #333;
          page-break-inside: avoid;
        }
        
        .summary-row {
          display: flex;
          justify-content: space-between;
          padding: 4px 0;
          font-size: 9pt;
        }
        
        .summary-row.total {
          font-weight: bold;
          font-size: 10pt;
          border-top: 2px solid #333;
          padding-top: 8px;
          margin-top: 8px;
        }
      }
    </style>
  `;
};

/**
 * Generate complete printable report HTML
 */
export const generatePrintableReport = ({
  title,
  filters = [],
  content,
  currentUser
}) => {
  return `
    <!DOCTYPE html>
    <html>
      <head>
        <meta charset="UTF-8">
        <title>${title}</title>
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap" rel="stylesheet">
        ${generateReportStyles()}
        <script>
          // Calculate page numbers after document loads
          window.addEventListener('load', function() {
            setTimeout(function() {
              // Calculate total pages based on content height and page size
              // Letter size: 11 inches height, minus margins (0.4in top + 0.75in bottom = 1.15in)
              // Usable height per page: 11 - 1.15 = 9.85 inches
              // At 96 DPI: 9.85 * 96 = 945.6 pixels per page
              const pageHeight = 945;
              const contentHeight = document.body.scrollHeight;
              const totalPages = Math.max(1, Math.ceil(contentHeight / pageHeight));
              
              // Inject the total pages directly into CSS using page counter
              const printStyle = document.createElement('style');
              printStyle.textContent = '.page-number::before { content: "Page " counter(page) " of ' + totalPages + '"; } body { counter-reset: page 1; }';
              document.head.appendChild(printStyle);
            }, 250);
          });
        </script>
      </head>
      <body>
        ${generateReportHeader(title, filters)}
        ${content}
        ${generateReportFooter(currentUser)}
      </body>
    </html>
  `;
};
